FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /api-server main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /api-server .

EXPOSE 8085
CMD ["./api-server"]
